# REFERENCIA https://github.com/Steven-Nagie/multi-module-spring-docker/blob/master/pom.xml
FROM maven:3.9.3-eclipse-temurin-17-alpine AS MAVEN_TOOL_CHAIN
COPY pom.xml /tmp/
COPY harvest-backend /tmp/harvest-backend/
COPY harvest-open-api /tmp/harvest-open-api/

WORKDIR /tmp/

RUN mvn clean install

FROM eclipse-temurin:17-jdk-alpine

COPY --from=MAVEN_TOOL_CHAIN /tmp/harvest-backend/target/harvest-backend-1.0-SNAPSHOT.jar app.jar

RUN sh -c 'touch /app.jar'


ENTRYPOINT ["java","-jar","/app.jar","--spring.profiles.active=prod"]

