openapi: 3.0.3

info:
  title: Harvest APIs
  description: Api para la gestion de recursos de una empresa viticultora
  version: 1.0-SNAPSHOT


servers:
  - url: http://localhost:8080

tags:
  - name: Autenticado
    description: Funcionalidades relacionadas el autenticado y modificación de datos de usuario

  - name: Usuario
    description: Funcionalidades para todos los usuarios

  - name: Administrador
    description: Funcionalidades de Administrador

  - name: Trabajadores
    description: Funcionalidades para la gestion de Trabajadores

  - name: Capataz
    description: Funcionalidades de Capataz

  - name: Tractorista
    description: Funcionalidades de Tractorista


paths:
  # Funcionalidades
  ###########################################################################################################
  /api/auth/signin:
    post:
      
      tags:
        - Autenticado
      summary: Autenticacion con usuario y contraseña
      operationId: signin
      requestBody:
        description: Credenciales para acceder a funcionalidades del sistema
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/SignInRequestDTO'
            example:
              username: validUsername
              password: ejemploPassword
      responses:
        200:
          description: Usuario y JWT
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/SignInResponseDTO'
              example:
                id: 1
                username: validUsername
                tokenType: Bearer
                accessToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtaWd1ZWxBZG1pbiIsImlhdCI6MTY5MjIzNDg3NiwiZXhwIjoxNjkyMjM0OTYyfQ.gfFLE9pE-HYLfG6_fgTj92CwsmkrTmUsQLz6D0s6IeB8KmqO0ue17ExUx3o7a-oebUr1BNnshtu-odZnANUu-A
                roles: [ "ROLE_ADMIN" ]

        400:
          description: Payload de signIn no valido
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                message: 'Datos no validos'
                status: 400
        401:
          description: Datos para login erroneos
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                message: Bad credentials
                status: 401

        429:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: To many requests
                status: 429

        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'


  /api/auth/{id}/changePassword:
    post:
      tags:
        - Autenticado
      security:
        - bearerAuth: [ ]
      summary: Cambio de contraseña
      operationId: changePassword
      x-custom-role:
        - ADMIN
        - CAPATAZ
        - TRACTORISTA
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
            maximum: 9223372036854775807
            minimum: 0
          required: true
          description: Id de usuario al que se realiza cambio de contraseña
      requestBody:
        description: Antigua contraseña y nueva contraseña
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/ChangePasswordDTO'
            example:
              oldPassword: 12345678
              newPassword: 87654321
      responses:
        200:
          description: Mensaje de cambio de contraseña exitoso
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/MessageResponseDTO'
              example:
                message: 'Contraseña cambiada'

        400:
          description: Payload de usuario no valido
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                message: 'Datos no validos'
                status: 400

        401:
          description: Error 401
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: Bad credentials
                status: 401

        429:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/{id}/changePassword
                error: Unauthorized
                message: To many requests
                status: 429
        default:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'

  /api/auth/{id}/updateUser:
    post:
      tags:
        - Autenticado
      security:
        - bearerAuth: [ ]
      summary: Actualizar datos de usuario
      operationId: updateUser
      x-custom-role:
        - ADMIN
        - CAPATAZ
        - TRACTORISTA
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
            maximum: 9223372036854775807
            minimum: 0
          required: true
          description: Id de usuario al que se realiza la actualizacion
      requestBody:
        description: Datos de usuario
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/UpdateUserDTO'
            example:
              email: juan@filo.com
              name: juan
              lastname: santiago
              dni: 12345678Q
              nss: 123456789012
              phone: 123456789
              birthdate: 1990-08-19

      responses:
        200:
          description: Exito en la actualizacion de datos de usuario
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/MessageResponseDTO'
              example:
                message: 'User updated successfully!'
        400:
          description: Payload de usuario no valido
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                message: 'Datos no validos'
                status: 400
        401:
          description: Error 401
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: Bad credentials
                status: 401
        409:
          description: Error 403
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/updateUser
                error: Conflict
                message: Conflict
                status: 409
        429:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/updateUser
                error: Unauthorized
                message: To many requests
                status: 429
        default:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'


  /api/auth/signup:
    post:
      tags:
        - Autenticado
      security:
        - bearerAuth: [ ]
      summary: Registrar un usuario ( Solo puede el administrador)
      operationId: signUp
      x-custom-role:
        - ADMIN

      requestBody:
        description: Datos de usuario
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/NewUserDTO'
            example:
              username: Juan
              password: 12345678
              roles: [ "capataz",
                       "tractorista" ]
              email: juan@filo.com
              name: juan
              lastname: santiago
              dni: 12345678Q
              nss: 123456789012
              phone: 123456789
              birthdate: 1990-08-19

      responses:
        201:
          description: Exito en el registro de usuario
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/MessageResponseDTO'
              example:
                message: 'User registered successfully!'
        400:
          description: Payload de registro invalido
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                message: 'Usuario no valido'
                status: 400

        401:
          description: Error 401
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: Bad credentials
                status: 401

        429:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: To many requests
                status: 429
        default:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'

  /api/workers:
    get:
      tags:
        - Trabajadores
      security:
        - bearerAuth: [ ]
      summary: Obtener resumen de trabajadores
      operationId: getWorkers
      x-custom-role:
        - ADMIN
        - CAPATAZ
        - TRACTORISTA

      responses:
        200:
          description: Listado de trabajadores
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/WorkerListDTO'

        401:
          description: Error 401
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: Bad credentials
                status: 401

        429:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: To many requests
                status: 429
        default:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'


    post:
      tags:
        - Trabajadores
      security:
        - bearerAuth: [ ]
      summary: Registrar un trabajador ( Solo puede el administrador)
      operationId: signUpWorker
      x-custom-role:
        - ADMIN
      requestBody:
        description: Datos de trabajador
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/NewWorkerDTO'
            example:
              name: juan
              lastname: santiago
              dni: 12345678Q
              nss: 123456789012
              phone: 123456789
              birthdate: 1990-08-19
              address: Ronda de Outeiro, nº 26 5ºA

      responses:
        201:
          description: Exito en el registro de Trabajador
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/MessageResponseDTO'
              example:
                message: 'Worker registered successfully!'
        400:
          description: Payload de registro invalido
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                message: 'Trabajador no valido'
                status: 400

        401:
          description: Error 401
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: Bad credentials
                status: 401

        429:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'
              example:
                path: /api/auth/signin
                error: Unauthorized
                message: To many requests
                status: 429
        default:
          description: Error 429
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Error'

security:
  - bearerAuth: [ ]

