server:
  port: 8080
#  ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

app:
  jwtcookie: harvest
  jwtSecret: harvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpring
  jwtExpirationMs: 86400