server:
  port: 8080

spring:
  sql:
    init:
      mode: always     # Siempre inicializa la base de datos
#      continue-on-error: true  # Continua sin acabar la ejecucion de spring-boot aun habiendo errores sql

  datasource:
    url: jdbc:mysql://localhost:3306/harvest_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: userHarvest
    password: harvestland



