server:
  port: 8080
#  ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

management:
  endpoints:
    web:
      cors:
        allow-origins: "*"
spring:
  sql:
    init:
      plataform: mysql
      mode: always     # Siempre inicializa la base de datos
#      continue-on-error: true  # Continua sin acabar la ejecucion de spring-boot aun habiendo errores sql

  datasource:
#    initialization-mode: always
    url: jdbc:mysql://localhost:3306/harvest_db?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: userHarvest
    password: harvestland
#    url: @dataSource.url@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: @dataSource.user@
#    password: @dataSource.password@


  jpa:
    defer-datasource-initialization: true
    hibernate:
      show_sql: true
      format_sql: true
#      ddl-auto: update
      ddl-auto: create-drop # Crea y dropea las tablas, no utilizar en un entorno de produccion

      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect  # Selecciona el dialecto específico de la base de datos

app:
  jwtcookie: Bu:GW8bgPlEw
  jwtSecret: harvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpring
  jwtExpirationMs: 86400
  jwtRefreshExpirationMs: 86400000

springdoc:
  show-login-endpoint: true
  #  api-docs:
  #    version: openapi_3_0

  swagger-ui:
    urlsPrimaryName: /v3/api-docs
    #    docExpansion: list
    persistAuthorization: true
    use-root-path: true
    disable-swagger-default-url: true
    tryItOutEnabled: true

#logging:
#  level:
#    org.hibernate.SQL: debug   # Establece el nivel de registro para las sentencias SQL a "info"
#    org.hibernate.type: debug  # Establece el nivel de registro para los tipos de datos de Hibernate a "info"

