openapi: 3.0.3

info:
  title: Harvest APIs
  description: |-
    API para la gestion de recursos de una empresa viticultora
  version: 1.0-SNAPSHOT


#servers:
#  - url:

paths:
  /api/test/all:
    get:
      summary: Visible para todos
      operationId: nada
      responses:
        200:
          description: Info de visibilidad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllDetailsDTO'
  /api/test2/capataz:
    get:
      summary: Visible para capataz
      operationId: capataz
      responses:
        200:
          description: Info de visibilidad de capataz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CapatazDetailsDTO'
        401:
          description: Acceso no autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/test2/tractor:
    get:
      summary: Visible para tractorista
      operationId: tractorista
      responses:
        200:
          description: Info de visibilidad de tractorista
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TractoristaDetailsDTO'
        401:
          description: Acceso no autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/test2/admin:
    get:
      summary: Visible para admin
      operationId: admin
      responses:
        200:
          description: Info de visibilidad de admin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminDetailsDTO'
        401:
          description: Acceso no autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        path:
          description: Path al error
          type: string
          nullable: false
          example: "/error"
        error:
          description: Codigo de error
          type: string
          nullable: false
          example: "Unauthorized"
        message:
          description: Mensaje de error explicativo
          type: string
          nullable: false
          example: "Full authentication is required to access this resource"
        status:
          description: No autorizado
          type: integer
          nullable: false
          example: 401
    AllDetailsDTO:
      type: string
      example: "ALL"
    CapatazDetailsDTO:
      type: string
      example: "Capataz"
    TractoristaDetailsDTO:
      type: string
      example: "Tractorista"
    AdminDetailsDTO:
      type: string
      example: "Admin"




