server:
  port: 8080
#  ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

app:
  jwtcookie: Bu:GW8bgPlEw
  jwtSecret: harvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpringharvestSpring
  jwtExpirationMs: 86400
  jwtRefreshExpirationMs: 86400000

springdoc:
  api-docs:
    path: /api-docs
#  use-management-port: true
  # This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
#  management:
#    server:
#      port: 9090
#    endpoints.web.exposure.include: openapi, swagger-ui